[package]
name = "broswer_view_vm"
version = "0.1.0"
authors = ["taochunyu <tao_chunyu@foxmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.60"
js-sys = "0.3.37"
render_vm = { path= "../.." }
