[package]
name = "web"
version = "0.1.0"
authors = ["taochunyu <tao_chunyu@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.60"
editor = { path = "../../editor" }
js-sys = "0.3.37"
