[package]
name = "editor"
version = "0.1.0"
authors = ["taochunyu <tao_chunyu@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui = { path = "../ui" }