[package]
name = "yew_web"
version = "0.1.0"
authors = ["taochunyu <tao_chunyu@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.11.0"
editor = { path = "../editor" }
stdweb = "0.4.20"
